### ISSUE TITLE
[MAINTAINABILITY] Fix maintainability

### ISSUE THREAD

**Issue by setiadijoe** [sapawarga/phonebook-service#40]
upgrade maintainability terkait code smells nya
saat ini ada 8 code smells, targetnya bisa diselesaikan dengan bantuan  ke kang @azophy @aldidoanta @firmanJS

**Comment by firmanJS** [comment]
yu bisa yuk tingal 14 issue lagi :laughing:

**Comment by setiadijoe** [comment]
issue yang ini buat nanti nextnya karena sekarang udah dapet A dari codeclimatenya juga, jadi tetep open

**Comment by setiadijoe** [comment]
yang terakhir ini code smells 2 dan duplication 7, tapi aku ragu yang duplication ini bisa dihandle karena sebetulnya itu udah yang practice yang umum, bukan yang best ya tapi yang umum. Belum nemu cara handlenya yang di bagian transport itu
